### PR TITLE
Handle error when unresolved system call

### PR DESCRIPTION
**Pull request by chethanah**
**Issue**
- When added to poststop hook with `--seccomp-profile` to generate seccomp profile, there maybe be `signal: segmentation fault (core dumped)`.
- This is because few system calls in the trace output are not resolved and returns null pointer leading seg fault.
```sh
# example in podman
$ podman --log-level=debug --hooks-dir="/etc/containers/oci/hooks.d/" run --annotation=oci-ftrace-syscall-analyzer/trace=true -it --rm docker.io/library/bash 
bash-5.1# exit
WARN[0003] container ee52710e8a5077e784d78f4d76c0f48342c4faaa449cd38a05e4fe2409fd12ee: poststop hook 0: executing [oci-ftrace-syscall-analyzer report --seccomp-profile /tmp/seccomp.json --output /tmp/ftrace_syscalls_dump.log]: signal: segmentation fault (core dumped) 

# example in runc
$ sudo runc run test 
bash-5.0# uname -a 
Linux runc 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
bash-5.0# exit
ERRO[0004] Running hook #0:: error running hook: signal: segmentation fault (core dumped), stdout: , stderr:  
```

   
**Fix**
- Handle error returned if the system call num⇨name is not resolved by the libseccomp crate.
- Additionally, using `libseccomp` crate ([libseccomp-rs](https://github.com/ManaSugi/libseccomp-rs)) instead of Rust FFI to convert syscall name from number.

### CODE REVIEW

**Comment by chethanah** [comment]
- Running tests manually - OK
```bash
# git branch 
* handle-err-unresolved-syscalls
  master

# git log --oneline -1 
c91fd0a (HEAD -> handle-err-unresolved-syscalls, origin/handle-err-unresolved-syscalls) Handle Err when unresolved syscall

# cargo test 
warning: unused import: `Write`
 --> tests/integ.rs:3:35
  |
3 | use std::io::{BufRead, BufReader, Write};
  |                                   ^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `std::process::Stdio`
 --> tests/integ.rs:4:5
  |
4 | use std::process::Stdio;
  |     ^^^^^^^^^^^^^^^^^^^

warning: 2 warnings emitted

    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running target/debug/deps/oci_ftrace_syscall_analyzer-84608faaf5240d42

running 5 tests
test report::test_remove_raw_syscall ... ok
test report::test_convert_syscall_id ... ok
test report::test_generate_profile ... ok
test report::test_convert_error_info ... ok
test utils::test_search_tracefs_path ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running target/debug/deps/integ-9e2282480bb145b0

running 11 tests
test integration::trace_does_not_start_with_annotations_false ... ok
test integration::trace_does_not_start_with_use_annots ... ok
test integration::trace_start ... ok
test integration::set_buffer_size ... ok
test integration::syscall_filter ... ok
test integration::report_conflict_between_livedump_and_profile ... ok
test integration::error_filter ... ok
test integration::report ... ok
test integration::report_profile ... ok
test integration::report_livedump ... ok
test integration::trace_start_with_annotations ... ok

test result: ok. 11 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.11s

```

**Comment by KentaTada** [comment]
@chethanah I think this error is resolved by your commit.
https://github.com/KentaTada/oci-ftrace-syscall-analyzer/pull/27
Could you rebase this commit and test it again?
Thanks.

**Comment by chethanah** [comment]
Hello @KentaTada 

 - I've rebased this branch 
 - The checks are passing. Please verify and merge.

Thank You   
Chethan

**Comment by KentaTada** [comment]
LGTM

**Pull request merged**
